name: flutter_skeleton
description: Flutter Skeleton

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  provider: ^6.0.3
  easy_localization: ^3.0.1
  firebase_auth: ^3.6.4
  firebase_core: ^1.21.0
  flutter_form_builder: ^7.6.0
  form_builder_validators: ^8.3.0
  sizer: ^2.0.15
  flutter_svg: ^1.1.4
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/translations/
    - assets/icons/
